repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.10.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.5
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
# TODO(rafska): add hook for astral-sh/ty when pre-commit officialy supported
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck